%
% desc07_42.m
% (max, +) system description
% automatically generated by phoebe ver.1.0 on 2019-10-13 16:46:20 
% Copyright (c) 2017-2019 Jarosław Stańczyk <j.stanczyk@hotmail.com>
%

clear
disp('equations:');
disp('x(k+1) = A0x(k+1) + A1x(k) + B1u(k)');
disp('y(k)   = Cx(k)');

disp('where:');
disp('u(k) = [ u_1(k); u_2(k); u_3(k); ]');
disp('x(k) = [ x_1(k); x_2(k); x_3(k); x_4(k); ]');
disp('y(k) = [ y_1(k); ]');

disp('initial vectors:');
U  = mp_ones(3, 1)
X0 = mp_zeros(4, 1)

disp('times:');
d1 = 3
d2 = 2
d3 = 6
d4 = 2
t01 = 0
t02 = 0
t03 = 0
t14 = 0
t24 = 1
t34 = 0
t45 = 0

disp('matrices:');
% matrix A0
A0 = mp_zeros(4, 4);
   A0(4, 1) = mp_multi(d1, t14);
   A0(4, 2) = mp_multi(d2, t24);
   A0(4, 3) = mp_multi(d3, t34);
   A0

% matrix A1
A1 = mp_zeros(4, 4);
   A1(1, 1) = d1;
   A1(2, 2) = d2;
   A1(3, 3) = d3;
   A1(4, 4) = d4;
   A1

% matrix B1
B1 = mp_zeros(4, 3);
   B1(1, 1) = t01;
   B1(2, 2) = t02;
   B1(3, 3) = t03;
   B1

% matrix C
C = mp_zeros(1, 4);
   C(1, 4) = mp_multi(d4, t45);
   C

disp('finally:');
disp('x(k+1) = Ax(k) + Bx(k)');
disp('where:');
As  = mp_star(A0)

% matrix A
As1 = mp_multi(As, A1);
A   = [
       As1;
      ]

% matrix B
Bs1 = mp_multi(As, B1);
B   = [
       Bs1;
      ]
disp('state vector and output:');
% k - number of iterations
k = 12;

X(:, 1) = mp_add(mp_multi(A, X0), mp_multi(B, U));
Y(:, 1) = mp_multi(C, X(:, 1));
for i = 2:k
    X(:, i) = mp_add(mp_multi(A, X(:, i - 1)), mp_multi(B, U));
    Y(:, i) = mp_multi(C, X(:, i));
end
X
Y

% eof

