%
% desc02_c.m
% (max, +) system description
% automatically generated by phoebe ver.1.0 on 2019-10-13 16:46:20 
% Copyright (c) 2017-2019 Jarosław Stańczyk <j.stanczyk@hotmail.com>
%

clear
disp('x(k+1) = A0x(k+1) + A1x(k) + B0u(k)');
disp('y(k) = Cx(k)');

disp('u(k) = [ u_1(k); ]');
disp('x(k) = [ x_1(k); x_2(k); x_3(k); ]');
disp('y(k) = [ y_1(k); ]');

disp('initial vectors:');
U  = mp_ones(1, 1)
X0 = mp_zeros(3, 1)

disp('times:');

disp('matrices:');
% matrix A0
A0 = mp_zeros(3, 3);
   A0(2, 1) = mp_multi(3, 2);
   A0(3, 2) = mp_multi(2, 2);
   A0

% matrix A1
A1 = mp_zeros(3, 3);
   A1(1, 1) = 3;
   A1(2, 2) = 2;
   A1(3, 3) = 6;
   A1

% matrix B0
B0 = mp_zeros(3, 1);
   B0(1, 1) = 1;
   B0

% matrix C
C = mp_zeros(1, 3);
   C(1, 3) = mp_multi(6, 1);
   C

disp('finally:');
As = mp_star(A0)
A = mp_multi(As, A1)
B = mp_multi(As, B0)

disp('state vector and output:');
% k - number of iterations
k = 12;

X(:, 1) = mp_add(mp_multi(A, X0), mp_multi(B, U));
Y(:, 1) = mp_multi(C, X(:, 1));
for i = 2:k
    X(:, i) = mp_add(mp_multi(A, X(:, i - 1)), mp_multi(B, U));
    Y(:, i) = mp_multi(C, X(:, i));
end
X
Y

% eof

