%
% desc05_22.m
% (max, +) system description
% automatically generated by phoebe ver.1.0 on 2019-10-13 16:46:20 
% Copyright (c) 2017-2019 Jarosław Stańczyk <j.stanczyk@hotmail.com>
%

clear
disp('equations:');
disp('x(k+1) = A0x(k+1) + A1x(k) + B1u(k)');
disp('y(k)   = Cx(k)');

disp('where:');
disp('u(k) = [ u_1(k); u_2(k); u_3(k); u_4(k); u_5(k); u_6(k); u_7(k); u_8(k); ]');
disp('x(k) = [ x_1(k); x_2(k); x_3(k); x_4(k); x_5(k); x_6(k); ]');
disp('y(k) = [ y_1(k); ]');

disp('initial vectors:');
U  = mp_ones(8, 1)
X0 = mp_zeros(6, 1)

disp('times:');
d1 = 43
d2 = 20
d3 = 15
d4 = 6
d7 = 21
d8 = 25

disp('matrices:');
% matrix A0
A0 = mp_zeros(6, 6);
   A0(4, 2) = d2;
   A0(5, 1) = d1;
   A0(5, 6) = d8;
   A0(6, 3) = d3;
   A0(6, 4) = d4;
   A0

% matrix A1
A1 = mp_zeros(6, 6);
   A1(1, 1) = d1;
   A1(1, 5) = 0;
   A1(2, 2) = d2;
   A1(2, 4) = 0;
   A1(3, 3) = d3;
   A1(3, 6) = 0;
   A1(4, 4) = d4;
   A1(4, 6) = 0;
   A1(5, 1) = 0;
   A1(5, 5) = d7;
   A1(6, 5) = 0;
   A1(6, 6) = d8;
   A1

% matrix B1
B1 = mp_zeros(6, 8);
   B1(1, 1) = 0;
   B1(1, 2) = 0;
   B1(2, 3) = 0;
   B1(2, 4) = 0;
   B1(3, 6) = 0;
   B1(3, 7) = 0;
   B1(4, 5) = 0;
   B1(6, 8) = 0;
   B1

% matrix C
C = mp_zeros(1, 6);
   C(1, 5) = d7;
   C

disp('finally:');
disp('x(k+1) = Ax(k) + Bx(k)');
disp('where:');
As  = mp_star(A0)

% matrix A
As1 = mp_multi(As, A1);
A   = [
       As1;
      ]

% matrix B
Bs1 = mp_multi(As, B1);
B   = [
       Bs1;
      ]
disp('state vector and output:');
% k - number of iterations
k = 12;

X(:, 1) = mp_add(mp_multi(A, X0), mp_multi(B, U));
Y(:, 1) = mp_multi(C, X(:, 1));
for i = 2:k
    X(:, i) = mp_add(mp_multi(A, X(:, i - 1)), mp_multi(B, U));
    Y(:, i) = mp_multi(C, X(:, i));
end
X
Y

% eof

