# -*- coding: utf-8 -*-
# pylama: ignore=E101
"""
	**answers.py**

	Copyright (c) 2017-2018 Jarosław Stańczyk <jaroslaw.stanczyk@upwr.edu.pl>
"""

GEN_TIME = '2018-01-21 08:30:33 CET'

ERR_ANS = '\
0: NOOP\n\
1: ERR_NO_INPUT_FILE\n\
2: ERR_NO_FILE\n\
3: ERR_NO_PERMISSION\n\
4: ERR_IO\n\
5: ERR_YAML\n\
6: ERR_NO_DATA\n\
7: ERR_NO_INPUT\n\
8: ERR_NO_OUTPUT\n\
9: ERR_NO_STATE_VECT\n'

INF_ANS = '\
Inf.VER:\n\
phoebe  v.0.8\n\
\n\
Inf.DOC:\n\
Usage:\tphoebe [--file] [--det1] [--det2] [--det3] [--vectors] [--latex | --no-desc] <desc_file>\n\
\tphoebe -h | --help\n\
\tphoebe -v | --version\n\
\n\
Options:\n\
  useful during debuging or learning:\n\
\t--file\t\tshows information from desc_file\n\
\t--det1\t\tshows parsed information (1) from desc_file\n\
\t--det2\t\tshows parsed information (2) from desc_file\n\
\t--det3\t\tshows mapping and parsed matrices\n\
\t--vectors\tshows vectors: u(k), x(k) and y(k)\n\
\t--no-desc\tdescription not generated\n\
  in everyday use:\n\
\t--latex\t\tgenerate description for latex (by default matlab model is generated)\n\
\t-h, --help\tdisplays this help message and exit\n\
\t-v, --version\tdisplays version information and exit\n'

INF_VER = '\
phoebe  v.0.8\n\
\n\
Author: Jaroslaw Stanczyk <jaroslaw.stanczyk@upwr.edu.pl>\n\
Copyright: (c) 2017-2018 Jaroslaw Stanczyk\n'

YML_ANS = '\
input:\n\
- u_1: {connect: M_1, op-time: t_u_1, tr-time: \'t_{0,1}\'}\n\
output:\n\
- y_1: {}\n\
prod-unit:\n\
- M_1: {connect: M_2, op-time: d_1, tr-time: \'t_{1,2}\'}\n\
- M_2: {connect: M_3, op-time: d_2, tr-time: \'t_{2,3}\'}\n\
- M_3: {connect: y_1, op-time: d_3, tr-time: \'t_{3,4}\'}\n\
values: {d_1: 3, d_2: 2, d_3: 6, \'t_{0,1}\': 1, \'t_{1,2}\': 2, \'t_{2,3}\': 0, \'t_{3,4}\': 1}\n\
\n'

ANS_FILE = '\
== INPUT FILE ==============\n\
output:\n\
- y_1: {}\n\
\n'

ANS_DET1_2 = '\
== DETAILS 1 ===============\n\
input: None\n\
prod-unit: None\n\
output: [{\'y_1\': {}}]\n\
values: None\n'

ANS_DET = '\
== DETAILS 1 ===============\n\
input: [\
{\'u\': {\'op-time\': \'0\', \'connect\': {\'M_1\': {\'tr-time\': \'t_{0,1}\', \'buffers\': \'-\'}}}}]\n\
prod-unit: [\
{\'M_1\': {\'op-time\': \'d_1\', \'connect\': {\'M_2\': {\'tr-time\': \'t_{1,2}\', \'buffers\': \'-\'}}}}, \
{\'M_2\': {\'op-time\': \'d_2\', \'connect\': {\'M_3\': {\'tr-time\': \'t_{2,3}\', \'buffers\': \'-\'}}}}, \
{\'M_3\': {\'op-time\': \'d_3\', \'connect\': {\'y\': {\'tr-time\': \'t_{3,4}\', \'buffers\': \'-\'}}}}]\n\
output: [\
{\'y\': {}}]\n\
values: %(values)s\n'

ANS_VALU_5 = '\
{\'t_{1,2}\': 2, \'t_{2,3}\': 0, \'d_2\': 2, \'d_3\': 6, \'d_1\': 3, \'t_{0,1}\': 1, \'t_{3,4}\': 1}'

ANS_DET1_4 = ANS_DET % {'values': None}
ANS_DET1_5 = ANS_DET % {'values': ANS_VALU_5}

ANS_DET2_2 = '\
== DETAILS 2 ===============\n\
input:\n\
prod-unit:\n\
output:\n\
  y_1\n\
    op-time: -\n\
    connect: -\n'

ANS_DET2 = '\
== DETAILS 2 ===============\n\
input:\n\
  u\n\
    op-time: 0\n\
    connect:\n\
      M_1\n\
        tr-time: t_{0,1}\n\
        buffers: -\n\
prod-unit:\n\
  M_1\n\
    op-time: d_1\n\
    connect:\n\
      M_2\n\
        tr-time: t_{1,2}\n\
        buffers: -\n\
  M_2\n\
    op-time: d_2\n\
    connect:\n\
      M_3\n\
        tr-time: t_{2,3}\n\
        buffers: -\n\
  M_3\n\
    op-time: d_3\n\
    connect:\n\
      y\n\
        tr-time: t_{3,4}\n\
        buffers: -\n\
output:\n\
  y\n\
    op-time: -\n\
    connect: -\n\
%(values)s'

ANS_DET2_4 = ANS_DET2 % {'values': ''}
ANS_DET2_5 = ANS_DET2 % {'values': '\
values:\n\
  d_1: 3\n\
  d_2: 2\n\
  d_3: 6\n\
  t_{0,1}: 1\n\
  t_{1,2}: 2\n\
  t_{2,3}: 0\n\
  t_{3,4}: 1\n'}

ANS_VEC2 = '\
== VECTORS =================\n\
u(k) = [ ]\n\
x(k) = [ ]\n\
y(k) = [ y_1(k) ]\n'

ANS_VEC4 = '\
== VECTORS =================\n\
u(k) = [ u(k) ]\n\
x(k) = [ x_1(k) x_2(k) x_3(k) ]\'\n\
y(k) = [ y(k) ]\n'

ANS_DET3_2 = '\
== DETAILS 3 ===============\n\
mapping:\n\
{\'y_1\': 0}\n\
None\n\
== MATRICES ================\n\
A0 = A1 = B0 = []\n\
A0 = A1 = B0 = []\n\
A0 = A1 = B0 = []\n\
C  = [\n\
[]\n\
]\n'

ANS_DET3 = '\
== DETAILS 3 ===============\n\
mapping:\n\
{\'M_3\': 2, \'M_2\': 1, \'M_1\': 0, \'u\': 0, \'y\': 0}\n\
%(values)s\n\
== MATRICES ================\n\
A0 = [\n[\'-\', \'-\', \'-\']\n[[\'d_1\', \'t_{1,2}\'], \'-\', \'-\']\n[\'-\', [\'d_2\', \'t_{2,3}\'], \'-\']\n]\n\
A1 = [\n[[\'d_1\'], \'-\', \'-\']\n[\'-\', [\'d_2\'], \'-\']\n[\'-\', \'-\', [\'d_3\']]\n]\n\
B0 = [\n[[\'t_{0,1}\']]\n[\'-\']\n[\'-\']\n]\n\
C  = [\n[\'-\', \'-\', [\'d_3\', \'t_{3,4}\']]\n]\n'

ANS_DET3_4 = ANS_DET3 % {'values': None}
ANS_DET3_5 = ANS_DET3 % {'values': ANS_VALU_5}

DESC_BEGIN = '\
%\n\
% (max, +) system description\n\
% Copyright (c) 2017-2018 Jaroslaw Stanczyk <jaroslaw.stanczyk@upwr.edu.pl>\n\
%\n\
% automatically generated by phoebe  v.0.8 on 2018-01-21 08:30:33 CET\n\
%\n'

ANS_MAT = '\
{0}\
\n\
clear\n\
disp(\'\');\n\
disp(\'x(k) = A0x(k) + A1x(k-1) + B0u(k)\');\n\
disp(\'y(k) =  Cx(k)\');\n\
disp(\'---------------------------------\');\n\
disp(\'u(k) = [ u(k); ]\');\n\
disp(\'x(k) = [ x_1(k); x_2(k); x_3(k); ]\');\n\
disp(\'y(k) = [ y(k); ]\');\n\
disp(\'---------------------------------\');\n\
\n\
disp(\'initial vectors:\');\n\
U  = mp_ones(1, 1)\n\
X0 = mp_zeros(3, 1)\n\
\n\
{1}\
disp(\'matrices:\');\n\
% matrix A0\n\
A0 = mp_zeros(3, 3);\n\
   A0(2, 1) = mp_multi(d1, t12);\n\
   A0(3, 2) = mp_multi(d2, t23);\n\
   A0\n\
\n\
% matrix A1\n\
A1 = mp_zeros(3, 3);\n\
   A1(1, 1) = d1;\n\
   A1(2, 2) = d2;\n\
   A1(3, 3) = d3;\n\
   A1\n\
\n\
% matrix B0\n\
B0 = mp_zeros(3, 1);\n\
   B0(1, 1) = t01;\n\
   B0\n\
\n\
% matrix C\n\
C = mp_zeros(1, 3);\n\
   C(1, 3) = mp_multi(d3, t34);\n\
   C\n\
\n\
disp(\'model:\');\n\
As = mp_star(A0)\n\
A = mp_multi(As, A1)\n\
B = mp_multi(As, B0)\n\
\n\
disp(\'state vector and output:\');\n\
% number of iterations\n\
k = 12;\n\
X(:, 1) = mp_add(mp_multi(A, X0), mp_multi(B, U));\n\
Y(:, 1) = mp_multi(C, X(:, 1));\n\
for i = 2:k\n\
    X(:, i) = mp_add(mp_multi(A, X(:, i - 1)), mp_multi(B, U));\n\
    Y(:, i) = mp_multi(C, X(:, i));\n\
end\n\
X\n\
Y\n\
\n\
% eof\n\
\n'

ANS_MAT4 = ANS_MAT.format(DESC_BEGIN, '')
ANS_MAT5 = ANS_MAT.format(DESC_BEGIN, '\
disp(\'times:\');\n\
d1 = 3\n\
d2 = 2\n\
d3 = 6\n\
t01 = 1\n\
t12 = 2\n\
t23 = 0\n\
t34 = 1\n\
\n')

ANS_LAT = '\
\\documentclass[11pt, a4paper, fleqn]{article}\n\
\\usepackage{amsmath}\n\
\\begin{document}\n\
\\section{(max, +) description}\n\
\n\
\\begin{align}\\begin{split}\n\
% x(k) = A0x(k) + A1x(k-1) + B0u(k)\n\
\\mathbf{x}(k) & \\, = \\; \
\\mathbf{A}_0\\mathbf{x}(k) \\oplus \\mathbf{A}_1\\mathbf{x}(k-1) \\oplus \\mathbf{B}_0\\mathbf{u}(k)\\\\\n\
% y(k) = Cx(k)\n\\mathbf{y}(k) & \\, = \\; \\mathbf{Cx}(k) \\\\\n\
\\end{split}\\end{align}\n\
\n\
% vector u(k)\n\
\\begin{equation*}\n\
\\mathbf{u}(k) = \n\
\\left[\\begin{array}{*{20}c}\n\
  u(k) \\\\\n\
\\end{array}\\right]\n\
\\end{equation*}\n\
\n\
% vector x(k)\n\
\\begin{equation*}\n\
\\mathbf{x}(k) = \n\
\\left[\\begin{array}{*{20}c}\n\
  x_1(k) \\\\\n\
  x_2(k) \\\\\n\
  x_3(k) \\\\\n\
\\end{array}\\right]\n\
\\end{equation*}\n\
\n\
% vector y(k)\n\
\\begin{equation*}\n\
\\mathbf{y}(k) = \n\
\\left[\\begin{array}{*{20}c}\n\
  y(k) \\\\\n\
\\end{array}\\right]\n\
\\end{equation*}\n\
\n\
% matrix A_0\n\
\\begin{equation*}\n\
\\mathbf{A}_0 = \n\
\\left[\\begin{array}{*{20}c}\n\
\\varepsilon \t& \\varepsilon \t& \\varepsilon \\\\\n\
d_1t_{1,2} \t& \\varepsilon \t& \\varepsilon \\\\\n\
\\varepsilon \t& d_2t_{2,3} \t& \\varepsilon \\\\\n\
\\end{array}\\right]\n\
\\end{equation*}\n\
\n\
% matrix A_1\n\
\\begin{equation*}\n\
\\mathbf{A}_1 = \n\
\\left[\\begin{array}{*{20}c}\n\
d_1 \t& \\varepsilon \t& \\varepsilon \\\\\n\
\\varepsilon \t& d_2 \t& \\varepsilon \\\\\n\
\\varepsilon \t& \\varepsilon \t& d_3 \\\\\n\
\\end{array}\\right]\n\
\\end{equation*}\n\
\n\
% matrix B_0\n\
\\begin{equation*}\n\
\\mathbf{B}_0 = \n\
\\left[\\begin{array}{*{20}c}\n\
t_{0,1} \\\\\n\
\\varepsilon \\\\\n\
\\varepsilon \\\\\n\
\\end{array}\\right]\n\
\\end{equation*}\n\
\n\
% matrix C_{}\n\
\\begin{equation*}\n\
\\mathbf{C}_{} = \n\
\\left[\\begin{array}{*{20}c}\n\
\\varepsilon \t& \\varepsilon \t& d_3t_{3,4} \\\\\n\
\\end{array}\\right]\n\
\\end{equation*}\n\
\n'

LAT_END = '\
\\end{document}\n\
% eof\n\
\n'

ANS_LAT4 = DESC_BEGIN + ANS_LAT + LAT_END
ANS_LAT5 = DESC_BEGIN + ANS_LAT + '\
\\noindent\\\\\n\
$d_1 = 3$\\\\\n\
$d_2 = 2$\\\\\n\
$d_3 = 6$\\\\\n\
$t_{0,1} = 1$\\\\\n\
$t_{1,2} = 2$\\\\\n\
$t_{2,3} = 0$\\\\\n\
$t_{3,4} = 1$\\\\\n\
\n' + LAT_END

ANS_MX0 = [
	['-', '-', '-', '-', '-', '-'],
	['-', '-', '-', '-', '-', '-'],
	['-', '-', '-', '-', '-', '-'],
	['-', '-', '-', '-', '-', '-'],
	['-', '-', '-', '-', '-', '-'],
	['-', '-', '-', '-', '-', '-'],
	['-', '-', '-', '-', '-', '-']
]

ANS_MX1 = [
	[['0', '0'], '-', '-', '-', '-', '-'],
	['-', '-', '-', '-', '-', '-'],
	['-', '-', '-', '-', '-', '-'],
	['-', '-', '-', '-', '-', '-'],
	['-', '-', '-', '-', '-', '-'],
	['-', '-', '-', '-', '-', '-'],
	['-', '-', '-', '-', '-', '-']
]

ANS_MX2 = [
	[['0', '0'], '-', '-', '-', ['0', '0'], '-'],
	['-', '-', '-', '-', '-', ['0', '0']],
	['-', ['0', '0'], '-', ['0', '0'], '-', '-'],
	['-', '-', '-', '-', '-', '-'],
	['-', '-', '-', '-', '-', '-'],
	['-', '-', ['0', '0'], '-', '-', '-'],
	['-', '-', '-', '-', '-', '-']
]

ANS_MX3 = [
	[['d_1'], '-', '-', '-', '-', '-', '-'],
	['-', ['d_2'], '-', '-', '-', '-', '-'],
	['-', '-', ['d_3'], '-', '-', '-', '-'],
	['-', '-', '-', ['d_4'], '-', '-', '-'],
	['-', '-', '-', '-', ['d_5'], '-', '-'],
	['-', '-', '-', '-', '-', ['d_6'], '-'],
	['-', '-', '-', '-', '-', '-', ['d_7']]
]

ANS_MX4 = [
	[['d_1'], ['0', 'd_2'], '-', '-', '-', '-', ['0', 'd_7']],
	['-', ['d_2'], '-', '-', ['0', 'd_5'], '-', '-'],
	['-', '-', ['d_3'], '-', ['0', 'd_5'], ['0', 'd_6'], '-'],
	['-', '-', '-', ['d_4'], '-', '-', '-'],
	['-', '-', '-', '-', ['d_5'], '-', '-'],
	['-', '-', '-', '-', '-', ['d_6'], ['0', 'd_7']],
	['-', '-', '-', '-', '-', '-', ['d_7']]
]

ANS_MX5 = [
	[['d_1'], ['d_2'], '-', '-', '-', '-', ['d_7']],
	['-', ['d_2'], '-', '-', ['d_5'], '-', '-'],
	['-', '-', ['d_3'], '-', ['d_5'], ['d_6'], '-'],
	['-', '-', '-', ['d_4'], '-', '-', '-'],
	['-', '-', '-', '-', ['d_5'], '-', '-'],
	['-', '-', '-', '-', '-', ['d_6'], ['d_7']],
	['-', '-', '-', '-', '-', '-', ['d_7']]
]

ANS_MX6 = [
	['-', ['d_6', '0', '0', '0'], ['0', 'd_7', '0', '0', '0']]
]
ANS_MX7 = [['-', ['d_6', '0'], ['d_7', '0']]]
ANS_MX8 = [['-', ['d_6'], ['d_7']]]

ANS_MX9 = [
	[['d_1'], '-', '-'],
	['-', ['d_2'], '-'],
	['-', '-', ['d_3']]
]

ANS_MX10 = [
	[['d_1'], '-', ['0', '0', '0', 't_{0,1}', 'd_3', 't_{3,4}']],
	['-', ['d_2'], ['0', '0', '0', 't_{0,2}', 'd_3', 't_{3,4}']],
	['-', '-', ['d_3']]
]

ANS_INP1 = [
	{'u_1': {'op-time': '0', 'connect': {'X_1': {'tr-time': '0', 'buffers': '-'}}}},
	{'u_2': {'op-time': '0', 'connect': {'X_3': {'tr-time': '0', 'buffers': '-'}}}},
	{'u_3': {'op-time': '0', 'connect': {'X_6': {'tr-time': '0', 'buffers': '-'}}}},
	{'u_4': {'op-time': '0', 'connect': {'X_3': {'tr-time': '0', 'buffers': '-'}}}},
	{'u_5': {'op-time': '0', 'connect': {'X_1': {'tr-time': '0', 'buffers': '-'}}}},
	{'u_6': {'op-time': '0', 'connect': {'X_2': {'tr-time': '0', 'buffers': '-'}}}}
]

ANS_INP2 = [
	{'u_1': {'op-time': '0', 'connect': {'M_1': {'tr-time': 't_{0,1}', 'buffers': '-'}}}},
	{'u_2': {'op-time': '0', 'connect': {'M_2': {'tr-time': 't_{0,2}', 'buffers': '-'}}}}
]

ANS_SYS1 = [
	{'X_1': {'op-time': 'd_1', 'connect': {
		'X_4': {'tr-time': '0', 'buffers': '-'},
		'X_2': {'tr-time': '0', 'buffers': '-'}}}},
	{'X_2': {'op-time': 'd_2', 'connect': {
		'X_5': {'tr-time': '0', 'buffers': '-'},
		'y_1': {'tr-time': '0', 'buffers': '-'}}}},
	{'X_3': {'op-time': 'd_3', 'connect': {
		'X_6': {'tr-time': '0', 'buffers': '-'},
		'X_4': {'tr-time': '0', 'buffers': '-'}}}},
	{'X_4': {'op-time': 'd_4', 'connect': {
		'X_7': {'tr-time': '0', 'buffers': '-'},
		'X_5': {'tr-time': '0', 'buffers': '-'}}}},
	{'X_5': {'op-time': 'd_5', 'connect': {
		'y_6': {'tr-time': '0', 'buffers': '-'},
		'y_2': {'tr-time': '0', 'buffers': '-'}}}},
	{'X_6': {'op-time': 'd_6', 'connect': {
		'X_7': {'tr-time': '0', 'buffers': '-'},
		'y_4': {'tr-time': '0', 'buffers': '-'}}}},
	{'X_7': {'op-time': 'd_7', 'connect': {
		'y_5': {'tr-time': '0', 'buffers': '-'},
		'y_3': {'tr-time': '0', 'buffers': '-'}}}}
]

ANS_SYS2 = [
	{'M_1': {'op-time': 'd_1', 'connect': {'M_3': {'tr-time': 't_{1,3}', 'buffers': '-'}}}},
	{'M_2': {'op-time': 'd_2', 'connect': {'M_3': {'tr-time': 't_{2,3}', 'buffers': '-'}}}},
	{'M_3': {'op-time': 'd_3', 'connect': {'y': {'tr-time': 't_{3,4}', 'buffers': '-'}}}}
]

ANS_OUT1 = [
	{'y_1': {'op-time': '0', 'connect': {'X_1': {'tr-time': '0', 'buffers': '-'}}}},
	{'y_2': {'op-time': '0', 'connect': {'X_3': {'tr-time': '0', 'buffers': '-'}}}},
	{'y_3': {'op-time': '0', 'connect': {'X_6': {'tr-time': '0', 'buffers': '-'}}}},
	{'y_4': {'op-time': '0', 'connect': {'X_3': {'tr-time': '0', 'buffers': '-'}}}},
	{'y_5': {'op-time': '0', 'connect': {'X_1': {'tr-time': '0', 'buffers': '-'}}}},
	{'y_6': {'op-time': '0', 'connect': {'X_2': {'tr-time': '0', 'buffers': '-'}}}}
]

ANS_OUT2 = [
	{'y': {'op-time': '0', 'connect': {
		'u_2': {'tr-time': '0', 'buffers': '-'},
		'u_1': {'tr-time': '0', 'buffers': '-'}
	}}}]

ANS_MAP1 = {
	'u_1': 0, 'u_2': 1, 'u_3': 2, 'u_4': 3, 'u_5': 4, 'u_6': 5,
	'X_1': 0, 'X_2': 1, 'X_3': 2, 'X_4': 3, 'X_5': 4, 'X_6': 5, 'X_7': 6,
	'y_1': 0, 'y_2': 1, 'y_3': 2, 'y_4': 3, 'y_5': 4, 'y_6': 5
}

ANS_MAP2 = {'u_1': 0, 'u_2': 1, 'M_1': 0, 'M_2': 1, 'M_3': 2, 'y': 0}

ANS_F7_DET1 = '\
== DETAILS 1 ===============\n\
input: [\
{\'u_1\': {\'op-time\': \'0\', \'connect\': {\'x_1\': {\'tr-time\': \'0\', \'buffers\': \'-\'}}}}, \
{\'u_2\': {\'op-time\': \'0\', \'connect\': {\'x_1\': {\'tr-time\': \'0\', \'buffers\': \'-\'}}}}]\n\
prod-unit: [\
{\'x_1\': {\'op-time\': \'0\', \'connect\': {\'x_2\': {\'tr-time\': \'o_{1,2}\', \'buffers\': \'-\'}}}}, \
{\'x_2\': {\'op-time\': \'0\', \'connect\': {\'x_4\': {\'tr-time\': \'o_{2,4}\', \'buffers\': \'-\'}, \'x_3\': {\'tr-time\': \'0\', \'buffers\': \'-\'}}}}, \
{\'x_3\': {\'op-time\': \'0\', \'connect\': {\'y_1\': {\'tr-time\': \'0\', \'buffers\': \'-\'}}}}, \
{\'x_4\': {\'op-time\': \'0\', \'connect\': {\'y_2\': {\'tr-time\': \'0\', \'buffers\': \'-\'}}}}]\n\
output: [\
{\'y_1\': {\'op-time\': \'0\', \'connect\': {\'u_1\': {\'tr-time\': \'0\', \'buffers\': \'-\'}}}}, \
{\'y_2\': {\'op-time\': \'0\', \'connect\': {\'u_2\': {\'tr-time\': \'0\', \'buffers\': \'-\'}}}}]\n\
values: {\'o_{1,2}\': 2, \'o_{2,4}\': 2}\n'

ANS_F7_DET3 = '\
== DETAILS 3 ===============\n\
mapping:\n\
{\'x_4\': 3, \'y_1\': 0, \'y_2\': 1, \'u_2\': 1, \'u_1\': 0, \'x_2\': 1, \'x_3\': 2, \'x_1\': 0}\n\
{\'o_{1,2}\': 2, \'o_{2,4}\': 2}\n\
== MATRICES ================\n\
A0 = [\n\
[\'-\', \'-\', \'-\', \'-\']\n\
[[\'o_{1,2}\'], \'-\', \'-\', \'-\']\n\
[\'-\', [\'o_{2,4}\'], \'-\', \'-\']\n\
[\'-\', [\'o_{2,4}\'], \'-\', \'-\']\n\
]\n\
A1 = [\n\
[[\'0\'], \'-\', [\'0\'], [\'0\']]\n\
[\'-\', [\'0\'], \'-\', \'-\']\n\
[\'-\', \'-\', [\'0\'], \'-\']\n\
[\'-\', \'-\', \'-\', [\'0\']]\n\
]\n\
B0 = [\n\
[[\'0\'], [\'0\']]\n\
[\'-\', \'-\']\n\
[\'-\', \'-\']\n\
[\'-\', \'-\']\n\
]\n\
C  = [\n\
[\'-\', \'-\', [\'0\'], \'-\']\n\
[\'-\', \'-\', \'-\', [\'0\']]\n\
]\n'

# end.
