#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
**info.py**
phoebe implementation: constant, statics and global variables

in the module:

* *class* **Info**

Copyright 2017 Jaroslaw Stanczyk, e-mail: jaroslaw.stanczyk@upwr.edu.pl
"""


class Inf(object):
	"""Static info generated by/for battleship"""
	# pylint: disable=too-few-public-methods

	def __init__(self):
		pass

	# used by setup
	AUTHOR = 'Jaroslaw Stanczyk'
	AUTHOR_EMAIL = 'jaroslaw.stanczyk@upwr.edu.pl'
	NAME = 'phoebe'
	DESC = NAME + ' - automatic max-plus description generator'
	LICENSE = 'GNU Affero General Public License v3 or later (AGPLv3+)'
	URL = 'http://gen.up.wroc.pl/stanczyk/'
	# 'https://github.com/stanczyk/phoebe'
	VERSION = '0.1'

	# used by phoebe
	VER = '' + \
		NAME + \
		': v.' + \
		VERSION
	WRITTEN = '' + \
		'author: ' + AUTHOR + '\n' + \
		'e-mail: ' + AUTHOR_EMAIL + '\n' + \
		'copyright: (c) 2017 ' + AUTHOR

	DOC = '' + \
		'Usage:' + \
		'\t' + NAME + ' [--file] ' + \
		'[--details-1] ' + \
		'[--details-2] ' + \
		'[--vectors] ' + \
		'<desc_file>\n' + \
		'\t' + NAME + ' -h | --help\n' + \
		'\t' + NAME + ' -v | --version\n' + \
		'\nOptions:\n' + \
		'\t-h, --help	shows this help message and exit.\n' + \
		'\t-v, --version	show version information and exit.'


def self_test():
	"""self tests"""
	print 'Inf.VER:'
	print Inf.VER + '\n'
	print 'Inf.DOC:'
	print Inf.DOC


if __name__ == '__main__':
	self_test()

# eof.
