# -*- coding: utf-8 -*-
"""
	**answers.ans_lat.py**

	Copyright (c) 2019 Jarosław Stańczyk <j.stanczyk@hotmail.com>
"""

LAT_BEGIN = '\
%\n\
% nazwa-pliku.tex\n\
% (max, +) system description\n\
% automatically generated by phoebe ver.1.0 on 2019-09-06 15:48:05 \n\
% Copyright (c) 2017-2019 Jarosław Stańczyk <j.stanczyk@hotmail.com>\n\
%\n\
\\documentclass[11pt, a4paper, fleqn]{article}\n\
\n\
\\usepackage{amsmath}\n\
\\usepackage{currfile}\n\
\\usepackage{graphicx}\n\
\n\
\\begin{document}\n\
\\noindent\n\
\\textbf{(max, +) description} \\texttt{\\currfilebase} \\\\\n\
% automatically generated by phoebe ver.1.0 on 2019-09-06 15:48:05 \n\
\n'

LAT_EQUEST1 = ''

# end.
