# -*- coding: utf-8 -*-
"""
	**answers.ans_lat.py**

	Copyright (c) 2019 Jarosław Stańczyk <j.stanczyk@hotmail.com>
"""

LAT_HEADER = '\
%\n\
% nazwa-pliku.tex\n\
% (max, +) system description\n\
% automatically generated by phoebe ver.1.0 on 2019-09-06 15:48:05 \n\
% Copyright (c) 2017-2019 Jarosław Stańczyk <j.stanczyk@hotmail.com>\n\
%\n'

LAT_END = '\
\n\
\\end{document}\n\
\n\
% eof\n\
\n'

LAT_PREFACE = '\
\n\
\\documentclass[11pt, a4paper, fleqn]{article}\n\
\n\
\\usepackage{amsmath}\n\
\\usepackage{currfile}\n\
\\usepackage{graphicx}\n\
\n\
\\begin{document}\n\
\n\
\\noindent\n\
\\textbf{(max, +) description of} \\texttt{\\currfilebase} \\\\\n\
automatically generated by phoebe ver.1.0 on 2019-09-06 15:48:05 \n'

LAT_EQ1 = '\n\
\\begin{align}\\begin{split}\n\
\\mathbf{x}(k+1) & \\, = \\; \\\\\n\
\\mathbf{y}(k) & \\, = \\; \n\
\\end{split}\\end{align}\n'

LAT_EQ2 = '\n\
\\begin{align}\\begin{split}\n\
\\mathbf{x}(k+1) & \\, = \\; \\mathbf{A}_{0}\\mathbf{x}(k+1) \\oplus \\mathbf{B}_{0}\\mathbf{u}(k)\\\\\n\
\\mathbf{y}(k) & \\, = \\; \\mathbf{Cx}(k) \\oplus \\mathbf{Du}(k)\n\
\\end{split}\\end{align}\n'

LAT_EQ3 = '\n\
\\begin{align}\\begin{split}\n\
\\mathbf{x}(k+1) & \\, = \\; \\mathbf{A}_{0}\\mathbf{x}(k+1) \\oplus \\mathbf{A}_{1}\\mathbf{x}(k) \\oplus \
\\mathbf{A}_{4}\\mathbf{x}(k-3) \\oplus \\mathbf{B}_{0}\\mathbf{u}(k)\\\\\n\
\\mathbf{y}(k) & \\, = \\; \\mathbf{Cx}(k) \\oplus \\mathbf{Du}(k)\n\
\\end{split}\\end{align}\n'

# end.
