# -*- coding: utf-8 -*-
"""
	**answers.ans_mat.py**

	Copyright (c) 2019 Jarosław Stańczyk <j.stanczyk@hotmail.com>
"""

MAT_HEADER = '\
%\n\
% nazwa-pliku.m\n\
% (max, +) system description\n\
% automatically generated by phoebe ver.1.0 on 2019-09-06 15:48:05 \n\
% Copyright (c) 2017-2019 Jarosław Stańczyk <j.stanczyk@hotmail.com>\n\
%\n'

MAT_PREFACE = '\
\n\
clear\n'

MAT_END = '\
\n\
% eof\n\
\n'

MAT_EQ1 = '\
disp(\'x(k+1) = \');\n\
disp(\'y(k) = \');\n'

MAT_EQ2 = '\
disp(\'x(k+1) = A0x(k+1) + B0u(k)\');\n\
disp(\'y(k) = Cx(k) + Du(k)\');\n'

MAT_EQ3 = '\
disp(\'x(k+1) = A0x(k+1) + A1x(k) + A4x(k-3) + B0u(k)\');\n\
disp(\'y(k) = Cx(k) + Du(k)\');\n'

MAT_VEC3 = '\n\
disp(\'u(k) = [ ]\');\n\
disp(\'x(k) = [ ]\');\n\
disp(\'y(k) = [ ]\');\n'

MAT_VEC4 = '\n\
disp(\'u(k) = [ u1(k); ]\');\n\
disp(\'x(k) = [ x1(k); x2(k); ]\');\n\
disp(\'y(k) = [ y1(k); y2(k); y3(k); ]\');\n'

# end.
