# -*- coding: utf-8 -*-
"""
	**answers.ans_mat.py**

	Copyright (c) 2019 Jarosław Stańczyk <j.stanczyk@hotmail.com>
"""

MAT_HEADER = '\
%\n\
% nazwa-pliku.m\n\
% (max, +) system description\n\
% automatically generated by phoebe ver.1.0 on 2019-09-06 15:48:05 \n\
% Copyright (c) 2017-2019 Jarosław Stańczyk <j.stanczyk@hotmail.com>\n\
%\n'

MAT_PREFACE = '\
\n\
clear\n'

MAT_END = '\
\n\
% eof\n\
\n'

# end.
