# -*- coding: utf-8 -*-
"""
	**answers.ans_cli.py**

	Copyright (c) 2019 Jarosław Stańczyk <j.stanczyk@hotmail.com>
"""
# flake8: noqa
# pylama: ignore=E101

ANS_HLP1 = '\
Usage: cli [OPTIONS] FILENAME COMMAND [ARGS]...\n\
\n\
  The max-plus algebraic state space model generator. Version 1.0. Copyright:\n\
  (c) 2017-2019 Jarosław Stańczyk <j.stanczyk@hotmail.com>\n\
\n\
Options:\n\
  --showfile  Display yaml information from FILENAME.\n\
  --det1      Show parsing information (1).\n\
  --det2      Show parsing information (2).\n\
  --det3      Show mapping and values for parsed matrices.\n\
  --matrices  Show max-plus model matrices.\n\
  --vectors   Show vectors: u(k), x(k) and y(k)\n\
  -h, --help  Show this message and exit.\n\
\n\
Commands:\n\
  latex   Generate latex description.\n\
  matlab  Max-plus matlab model, default action if no command is given.\n'

ANS_HLP2 = '\
Usage: cli [OPTIONS] FILENAME COMMAND [ARGS]...\n\
Try \"cli -h\" for help.\n\
\n\
Error: Missing argument "FILENAME".\n'

ANS_FILE = '\
== INPUT FILE ==============\n\
file_name: tests/samples/cli1.yml\n\
input:\n\
- u_1:\n\
    connect: M_1\n\
    tr-time: t_{0,1}\n\
- u_2:\n\
    connect: M_2\n\
    tr-time: t_{0,2}\n\
output:\n\
- y: {}\n\
prod-unit:\n\
- M_1:\n\
    connect: M_3\n\
    op-time: d_1\n\
    tr-time: t_{1,3}\n\
- M_2:\n\
    connect: M_3\n\
    op-time: d_2\n\
    tr-time: t_{2,3}\n\
- M_3:\n\
    connect: y\n\
    op-time: d_3\n\
    tr-time: t_{3,4}\n\
values:\n\
  d_1: 5\n\
  d_2: 6\n\
  d_3: 3\n\
  t_{0,1}: 2\n\
  t_{0,2}: 0\n\
  t_{1,3}: 1\n\
  t_{2,3}: 0\n\
  t_{3,4}: 0\n\
\n'

ANS_VEC1 = '\
== VECTORS =================\n\
u(k) = [ u_1(k) u_2(k) ]\'\n\
x(k) = [ x_1(k) x_2(k) x_3(k) ]\'\n\
y(k) = [ y_1(k) ]\'\n\
\n'

ANS_VEC2 = '\
== VECTORS =================\n\
u(k) = []\n\
x(k) = []\n\
y(k) = [ y_1(k) ]\'\n\
\n'

ANS_DET1_1 = '\
== DETAILS 1 ===============\n\
input: [\
{\'u_1\': {\'connect\': {\'M_1\': {\'tr-time\': \'t_{0,1}\', \'buffers\': \'-\'}}, \'op-time\': \'0\'}}, \
{\'u_2\': {\'connect\': {\'M_2\': {\'tr-time\': \'t_{0,2}\', \'buffers\': \'-\'}}, \'op-time\': \'0\'}}]\n\
prod-unit: [\
{\'M_1\': {\'connect\': {\'M_3\': {\'tr-time\': \'t_{1,3}\', \'buffers\': \'-\'}}, \'op-time\': \'d_1\'}}, \
{\'M_2\': {\'connect\': {\'M_3\': {\'tr-time\': \'t_{2,3}\', \'buffers\': \'-\'}}, \'op-time\': \'d_2\'}}, \
{\'M_3\': {\'connect\': {\'y\': {\'tr-time\': \'t_{3,4}\', \'buffers\': \'-\'}}, \'op-time\': \'d_3\'}}]\n\
output: [\
{\'y\': {}}]\n\
values: \
{\'t_{0,1}\': 2, \'t_{0,2}\': 0, \'t_{1,3}\': 1, \'t_{2,3}\': 0, \'t_{3,4}\': 0, \'d_1\': 5, \'d_2\': 6, \'d_3\': 3}\n\
\n'

ANS_DET1_2 = '\
== DETAILS 1 ===============\n\
input: None\n\
prod-unit: None\n\
output: [{\'y_1\': {}}]\n\
values: None\n\
\n'

ANS_DET2_1 = '\
== DETAILS 2 ===============\n\
input: \n\
  u_1\n\
    op-time: 0\n\
    connect:\n\
      M_1\n\
        tr-time: t_{0,1}\n\
        buffers: -\n\
  u_2\n\
    op-time: 0\n\
    connect:\n\
      M_2\n\
        tr-time: t_{0,2}\n\
        buffers: -\n\
prod-unit: \n\
  M_1\n\
    op-time: d_1\n\
    connect:\n\
      M_3\n\
        tr-time: t_{1,3}\n\
        buffers: -\n\
  M_2\n\
    op-time: d_2\n\
    connect:\n\
      M_3\n\
        tr-time: t_{2,3}\n\
        buffers: -\n\
  M_3\n\
    op-time: d_3\n\
    connect:\n\
      y\n\
        tr-time: t_{3,4}\n\
        buffers: -\n\
output: \n\
  y\n\
    op-time: -\n\
    connect: -\n\
values:\n\
  d_1: 5\n\
  d_2: 6\n\
  d_3: 3\n\
  t_{0,1}: 2\n\
  t_{0,2}: 0\n\
  t_{1,3}: 1\n\
  t_{2,3}: 0\n\
  t_{3,4}: 0\n\
\n'

ANS_DET2_2 = '\
== DETAILS 2 ===============\n\
input: \n\
prod-unit: \n\
output: \n\
  y_1\n\
    op-time: -\n\
    connect: -\n\
\n'

ANS_DET3_1 = '\
== DETAILS 3 ===============\n\
mapping: {\'u_1\': 0, \'u_2\': 1, \'M_1\': 0, \'M_2\': 1, \'M_3\': 2, \'y\': 0}\n\
values: {\'t_{0,1}\': 2, \'t_{0,2}\': 0, \'t_{1,3}\': 1, \'t_{2,3}\': 0, \'t_{3,4}\': 0, \'d_1\': 5, \'d_2\': 6, \'d_3\': 3}\n\
\n'

ANS_DET3_2 = '\
== DETAILS 3 ===============\n\
mapping: {\'y_1\': 0}\n\
values: None\n\
\n'

ANS_MAT1 = '\
== MATRICES ================\n\
A0 = [\n\
[\'-\', \'-\', \'-\']\n\
[\'-\', \'-\', \'-\']\n\
[[\'d_1\', \'t_{1,3}\'], [\'d_2\', \'t_{2,3}\'], \'-\']\n\
]\n\
A1 = [\n\
[[\'d_1\'], \'-\', \'-\']\n\
[\'-\', [\'d_2\'], \'-\']\n\
[\'-\', \'-\', [\'d_3\']]\n\
]\n\
B0 = [\n\
[\'-\', \'-\']\n\
[\'-\', \'-\']\n\
[\'-\', \'-\']\n\
]\n\
B1 = [\n\
[[\'t_{0,1}\'], \'-\']\n\
[\'-\', [\'t_{0,2}\']]\n\
[\'-\', \'-\']\n\
]\n\
C  = [\n\
[\'-\', \'-\', [\'d_3\', \'t_{3,4}\']]\n\
]\n\
D  = [\n\
[\'-\', \'-\']\n\
]\n\
\n'

ANS_MAT2 = '\
== MATRICES ================\n\
A0 = []\n\
A1 = []\n\
A0 = []\n\
A1 = []\n\
D  = [\n\
[]\n\
]\n\
D  = [\n\
[]\n\
]\n\
\n'

CLI_DESC2_LAT = '\
%\n\
% desc02_b.tex\n\
% (max, +) system description\n\
% automatically generated by phoebe ver.1.0 on 2019-10-13 11:56:24 \n\
% Copyright (c) 2017-2019 Jarosław Stańczyk <j.stanczyk@hotmail.com>\n\
%\n\
\n\
\\documentclass[11pt, a4paper, fleqn]{article}\n\
\n\
\\usepackage{amsmath}\n\
\\usepackage{currfile}\n\
\\usepackage{graphicx}\n\
\n\
\\begin{document}\n\
\n\
\\noindent\n\
\\textbf{(max, +) description of} \\texttt{\\currfilebase} \\\\\n\
automatically generated by phoebe ver.1.0 on 2019-10-13 11:56:24 \n\
\n\
\\begin{align}\\begin{split}\n\
\\mathbf{x}(k+1) & \\, = \\; \\mathbf{A}_{0}\\mathbf{x}(k+1) \\oplus \\mathbf{A}_{1}\\mathbf{x}(k) \\oplus \\mathbf{B}_{1}\\mathbf{u}(k)\\\\\n\
\\mathbf{y}(k) & \\, = \\; \\mathbf{Cx}(k)\n\
\\end{split}\\end{align}\n\
\n\
% vector u(k)\n\
\\begin{equation*}\n\
\\mathbf{u}(k) = \n\
\\left[\\begin{array}{*{20}c}\n\
  u_1(k) \\\\\n\
\\end{array}\\right]\n\
\\end{equation*}\n\
% vector x(k)\n\
\\begin{equation*}\n\
\\mathbf{x}(k) = \n\
\\left[\\begin{array}{*{20}c}\n\
  x_1(k) \\\\\n\
  x_2(k) \\\\\n\
  x_3(k) \\\\\n\
\\end{array}\\right]\n\
\\end{equation*}\n\
% vector y(k)\n\
\\begin{equation*}\n\
\\mathbf{y}(k) = \n\
\\left[\\begin{array}{*{20}c}\n\
  y_1(k) \\\\\n\
\\end{array}\\right]\n\
\\end{equation*}\n\
\\noindent\\\\\n\
times:\\\\\n\
$d_1 = 3$, $d_2 = 2$, $d_3 = 6$, $t_{0,1} = 1$, $t_{1,2} = 2$, $t_{2,3} = 0$, $t_{3,4} = 1$.\\\\\n\
\\\\\n\
matrices:\n\
% matrix A_{0}\n\
\\begin{equation*}\n\
\\mathbf{A}_{0} = \n\
\\left[\\begin{array}{ ccc }\n\
\\varepsilon	&\\varepsilon	&\\varepsilon\\\\\n\
d_1t_{1,2}	&\\varepsilon	&\\varepsilon\\\\\n\
\\varepsilon	&d_2t_{2,3}	&\\varepsilon\\\\\n\
\\end{array}\\right]\n\
\\end{equation*}\n\
\n\
% matrix A_{1}\n\
\\begin{equation*}\n\
\\mathbf{A}_{1} = \n\
\\left[\\begin{array}{ ccc }\n\
d_1	&\\varepsilon	&\\varepsilon\\\\\n\
\\varepsilon	&d_2	&\\varepsilon\\\\\n\
\\varepsilon	&\\varepsilon	&d_3\\\\\n\
\\end{array}\\right]\n\
\\end{equation*}\n\
\n\
% matrix B_{1}\n\
\\begin{equation*}\n\
\\mathbf{B}_{1} = \n\
\\left[\\begin{array}{ c }\n\
t_{0,1}\\\\\n\
\\varepsilon\\\\\n\
\\varepsilon\\\\\n\
\\end{array}\\right]\n\
\\end{equation*}\n\
\n\
% matrix C_{{}}\n\
\\begin{equation*}\n\
\\mathbf{C}_{{}} = \n\
\\left[\\begin{array}{ ccc }\n\
\\varepsilon	&\\varepsilon	&d_3t_{3,4}\\\\\n\
\\end{array}\\right]\n\
\\end{equation*}\n\
\n\
\n\
\\end{document}\n\
\n\
% eof\n\
\n'

CLI_DESC2_MAT = '\
%\n\
% desc02_b.m\n\
% (max, +) system description\n\
% automatically generated by phoebe ver.1.0 on 2019-10-13 11:56:24 \n\
% Copyright (c) 2017-2019 Jarosław Stańczyk <j.stanczyk@hotmail.com>\n\
%\n\
\n\
clear\n\
disp(\'x(k+1) = A0x(k+1) + A1x(k) + B1u(k)\');\n\
disp(\'y(k) = Cx(k)\');\n\
\n\
disp(\'u(k) = [ u_1(k); ]\');\n\
disp(\'x(k) = [ x_1(k); x_2(k); x_3(k); ]\');\n\
disp(\'y(k) = [ y_1(k); ]\');\n\
\n\
disp(\'initial vectors:\');\n\
U  = mp_ones(1, 1)\n\
X0 = mp_zeros(3, 1)\n\
\n\
disp(\'times:\');\n\
d1 = 3\n\
d2 = 2\n\
d3 = 6\n\
t01 = 1\n\
t12 = 2\n\
t23 = 0\n\
t34 = 1\n\
\n\
disp(\'matrices:\');\n\
% matrix A0\n\
A0 = mp_zeros(3, 3);\n\
   A0(2, 1) = mp_multi(d1, t12);\n\
   A0(3, 2) = mp_multi(d2, t23);\n\
   A0\n\
\n\
% matrix A1\n\
A1 = mp_zeros(3, 3);\n\
   A1(1, 1) = d1;\n\
   A1(2, 2) = d2;\n\
   A1(3, 3) = d3;\n\
   A1\n\
\n\
% matrix B1\n\
B1 = mp_zeros(3, 1);\n\
   B1(1, 1) = t01;\n\
   B1\n\
\n\
% matrix C\n\
C = mp_zeros(1, 3);\n\
   C(1, 3) = mp_multi(d3, t34);\n\
   C\n\
\n\
disp(\'finally:\');\n\
As = mp_star(A0)\n\
A = mp_multi(As, A1)\n\
B = mp_multi(As, B1)\n\
\n\
disp(\'state vector and output:\');\n\
% k - number of iterations\n\
k = 12;\n\
\n\
X(:, 1) = mp_add(mp_multi(A, X0), mp_multi(B, U));\n\
Y(:, 1) = mp_multi(C, X(:, 1));\n\
for i = 2:k\n\
    X(:, i) = mp_add(mp_multi(A, X(:, i - 1)), mp_multi(B, U));\n\
    Y(:, i) = mp_multi(C, X(:, i));\n\
end\n\
X\n\
Y\n\
\n\
% eof\n\
\n'

# end.
