#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
**latex.py**
phoebe implementation

in the module:
* *class* **Latex**

Copyright 2017 Jaroslaw Stanczyk, e-mail: jaroslaw.stanczyk@upwr.edu.pl
"""
import inf
from err import Err


class Lat(object):
	"""Lat class"""
	def __init__(self):
		pass

	@staticmethod
	def begin():
		info = inf.Inf()
		print '%'
		print '% (max, +) system description'
		print '% (c) 2017 {0}, e-mail: {1}'.format(info.AUTHOR, info.AUTHOR_EMAIL)
		print '%'
		print '% automatically generated by {0} on {1}'.format(info.VER, info.get_time())
		print '%'
		print '\\documentclass[11pt, a4paper, fleqn]{article}'
		print '\\usepackage{amsmath}'
		print '\\begin{document}'
		print '\\section{(max, +) description}'
		print
		return Err.NOOP

	@staticmethod
	def equation():
		print '\\begin{align}\\begin{split}\n' + \
			'% x(k) = A0x(k) + A1x(k-1) + B0u(k)\n' + \
			'\\mathbf{x}(k) & \\, = \\; ' + \
			'\\mathbf{A}_0\\mathbf{x}(k) \\oplus ' + \
			'\\mathbf{A}_1\\mathbf{x}(k-1) \\oplus ' + \
			'\\mathbf{B}_0\\mathbf{u}(k)\\\\\n' + \
			'% y(k) = Cx(k)\n' + \
			'\\mathbf{y}(k) & \\, = \\; \\mathbf{Cx}(k) \\\\\n' + \
			'\\end{split}\\end{align}\n'
		return Err.NOOP

	@staticmethod
	def vector(name, vector):
		print '% vector {0}(k)'.format(name)
		print '\\begin{equation*}'
		print '\\mathbf{%s}(k) = ' % name
		print '\\left[\\begin{array}{*{20}c}'
		for i in range(0, len(vector)):
			print '  {0}(k) \\\\'.format(vector[i])
		print '\\end{array}\\right]'
		print '\\end{equation*}\n'
		return Err.NOOP

	@staticmethod
	def matrix(name, idx_name, matrix):
		print '% matrix {0}_{1}'.format(name, idx_name)
		print '\\begin{equation*}'
		print '\\mathbf{%s}_%s = ' % (name, idx_name)
		print '\\left[\\begin{array}{*{20}c}'
		for i in range(0, len(matrix)):
			for j in range(0, len(matrix[i])):
				if j > 0:
					print '\t&',
				if matrix[i][j] == '-':
					print '\\varepsilon',
				else:
					print matrix[i][j],
			print '\\\\'
		print '\\end{array}\\right]'
		print '\\end{equation*}\n'
		return Err.NOOP

	@staticmethod
	def values(values):
		if values:
			print '\\noindent\\\\'
			for key in sorted(values):
				print '$%s = %s$\\\\' % (key, values[key])
			print
		return Err.NOOP

	@staticmethod
	def end():
		print '\\end{document}\n' + \
			'% eof\n'
		return Err.NOOP

# eof.
