#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
**info.py**
phoebe implementation: constant, statics and global variables

in the module:

* *class* **Info**

Copyright 2017 Jaroslaw Stanczyk, e-mail: jaroslaw.stanczyk@upwr.edu.pl
"""
import yaml


class Info(object):
	"""Static info generated by/for battleship"""

	def __init__(self):
		pass

	# used by setup
	AUTHOR = 'Jaroslaw Stanczyk'
	AUTHOR_EMAIL = 'jaroslaw.stanczyk@upwr.edu.pl'
	NAME = 'phoebe'
	DESC = NAME + ' - automatic max-plus description generator'
	LICENSE = 'GNU Affero General Public License v3 or later (AGPLv3+)'
	URL = 'http://gen.up.wroc.pl/stanczyk/'
	# 'https://github.com/stanczyk/phoebe'
	VERSION = '0.1'

	# used by phoebe
	VER = '' + \
		NAME + \
		': v.' + \
		VERSION
	WRITTEN = '' + \
		'author: ' + AUTHOR + '\n' + \
		'e-mail: ' + AUTHOR_EMAIL + '\n' + \
		'copyright: (c) 2017 ' + AUTHOR

	DOC = '' + \
		'Usage:' + \
		'\t' + NAME + ' <desc_file>\n' + \
		'\t' + NAME + ' -h | --help\n' + \
		'\t' + NAME + ' -v | --version\n' + \
		'\nOptions:\n' + \
		'\t-h, --help	shows this help message and exit.\n' + \
		'\t-v, --version	show version information and exit.'

	@staticmethod
	def dump(data, **kwargs):
		""" Simple wrapper to use the safety yaml dump function. """
		return yaml.safe_dump(data, **kwargs)

	def show(self, data, **kwargs):
		""" show data """
		print self.dump(data, **kwargs)


def self_test():
	"""self tests"""
	print 'Info.VER:'
	print Info.VER + '\n'
	print 'Info.DOC:'
	print Info.DOC


if __name__ == '__main__':
	self_test()

# eof.
